# .github/workflows/build-and-deploy.yml
name: Build with Docker Compose & Deploy via SFTP

on:
  push:
    branches: [build_pipeline]

concurrency:
  group: build-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Build with Docker Compose
        run: cd docker && chmod +x build.sh buildall.sh && ./build.sh && cd ..

      - name: Disable man_db updates (it slows down the build)
        run: echo "set man-db/auto-update false" | sudo debconf-communicate && sudo dpkg-reconfigure man-db

      - name: Install LFTP client
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via SFTP
        env:
          HOST: ${{ secrets.SITE_SERVER }}
          USER: ${{ secrets.SITE_USERNAME }}
          LFTP_PASSWORD: ${{ secrets.SITE_PASSWORD }}
        run: lftp --env-password sftp://${USER}@${HOST} -e "set sftp:auto-confirm yes; lcd dist_html; mirror -R . dev; bye"
